# Generated by Django 4.0.2 on 2022-02-22 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blok', '0012_alter_drivers_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Ф.И.O')),
                ('organization', models.CharField(choices=[('Нур Транс', 'Нур Транс'), ('Кармана Транс', 'Кармана Транс')], max_length=255, verbose_name='Уюшма номи')),
                ('car_brend', models.CharField(max_length=255, verbose_name='Aвтомашина русуми')),
                ('car_number', models.CharField(max_length=8, unique=True, verbose_name='Давлат белгиси')),
                ('date_given', models.DateField(verbose_name='Лицензия олган сана')),
                ('deadline', models.DateField(verbose_name='Лицензия муддати')),
                ('number_license', models.CharField(max_length=15, verbose_name='Лицензия рақами')),
                ('phone_number', models.CharField(max_length=9, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Cписка',
                'verbose_name_plural': 'Cписка',
            },
        ),
        migrations.RemoveField(
            model_name='litsence',
            name='car_state_number',
        ),
        migrations.AlterModelOptions(
            name='putyovka',
            options={'ordering': ('-date',), 'verbose_name': 'Путёвки', 'verbose_name_plural': 'Путёвки'},
        ),
        migrations.RemoveField(
            model_name='putyovka',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='putyovka',
            name='state_number',
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
        migrations.DeleteModel(
            name='Drivers',
        ),
        migrations.DeleteModel(
            name='Litsence',
        ),
        migrations.AddField(
            model_name='putyovka',
            name='car_number',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.DO_NOTHING, to='blok.list', verbose_name='Hомер автомобиля'),
            preserve_default=False,
        ),
    ]
